trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script:
    pip install selenium
    apt install chromium-chromedriver
    cp /usr/lib/chromium-browser/chromedriver /usr/bin

  displayName: 'Install selenium'

- script:  
    python selenium.py

  displayName: 'Run tests'
