trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script:
    pip install selenium 

    npm install chromedriver     

  displayName: 'Install selenium'

- script:  
    python selenium_tests.py

  displayName: 'Run tests'
